### ISSUE TITLE
Incompatible with Minecraft 1.13+ (as 'The Flattening' changed the block ID)

### ISSUE THREAD

**Issue by LXYan2333** [cbs228/nbtschematic#1]
Mojang changed the block ID so I can't use command like `sf.blocks[2, 3, 0] = 'minecraft:chest'` to add a chest.
reference:[Minecraft Wiki](https://minecraft.gamepedia.com/Java_Edition_1.13/Flattening)

**Comment by cbs228** [comment]
This package authors [MCEdit](https://www.mcedit.net/about.html) schematics. MCEdit schematic files only support the "[pre-flattening](https://minecraft.gamepedia.com/Java_Edition_data_values/Pre-flattening)" data values. MCEdit itself does not support Minecraft 1.13. Even the latest version only supports 1.11, but I have gotten it to work with 1.12 worlds.

Is there a schematic file format for Minecraft 1.13? If so, where is it published? What program or mod are you attempting to use this with?
