### ISSUE TITLE
nbtschematic nithub error

### ISSUE THREAD

**Issue by kofi2022** [cbs228/nbtschematic#3]
Requirement already satisfied: nbtlib in c:\users\naudi\appdata\local\programs\python\python36\lib\site-packages (1.2.4)
Collecting numpy==1.15.4 (from nbtlib)
  Using cached https://files.pythonhosted.org/packages/51/70/7096a735b27359dbc0c380b23b9c9bd05fea62233f95849c43a6b02c5f40/numpy-1.15.4-cp36-none-win_amd64.whl
nbtschematic 0.1.0 has requirement numpy~=1.14.5, but you'll have numpy 1.15.4 which is incompatible.
Installing collected packages: numpy
  Found existing installation: numpy 1.14.6
    Uninstalling numpy-1.14.6:
      Successfully uninstalled numpy-1.14.6
Successfully installed numpy-1.15.4
You are using pip version 10.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\naudi>from nbtschematic import SchematicFile
'from' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\naudi>sf = SchematicFile.load('tests/test_schematic/simple.schematic')
'sf' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\naudi>print("The block at Y=%d, Z=%d, X=%d has block ID %d" %
Unable to initialize device PRN

C:\Users\naudi>pip install nbtschematic==0.1.0
Requirement already satisfied: nbtschematic==0.1.0 in c:\users\naudi\appdata\local\programs\python\python36\lib\site-packages (0.1.0)
Requirement already satisfied: nbtlib~=1.2.1 in c:\users\naudi\appdata\local\programs\python\python36\lib\site-packages (from nbtschematic==0.1.0) (1.2.4)
Collecting numpy~=1.14.5 (from nbtschematic==0.1.0)
  Using cached https://files.pythonhosted.org/packages/dc/99/f824a73251589d9fcef2384f9dd21bd1601597fda92ced5882940586ec37/numpy-1.14.6-cp36-none-win_amd64.whl
nbtlib 1.2.4 has requirement numpy==1.15.4, but you'll have numpy 1.14.6 which is incompatible.
Installing collected packages: numpy
  Found existing installation: numpy 1.15.4
    Uninstalling numpy-1.15.4:
      Successfully uninstalled numpy-1.15.4
Successfully installed numpy-1.14.6
You are using pip version 10.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\naudi>from nbtschematic import SchematicFile
'from' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\naudi>sf = SchematicFile(shape=(10, 8, 4))
'sf' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\naudi>assert sf.blocks.shape == (10, 8, 4)
'assert' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\naudi>sf.blocks[2, 3, 0] = 42
'sf.blocks[2' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\naudi>sf.save('example.schematic')

**Comment by cbs228** [comment]
Hello,

There are several issues at play here. Some may stem from the limited installation instructions I have provided.

First, `nbtschematic` requires a different version of numpy than your system already has installed. Python's packaging system isn't very good, and different versions of the same package can't coexist in the same installation. When you're installing python programs, it is generally a good idea to install each one in its own **virtual environment**. Try following this [virtual environment tutorial](https://docs.python.org/3/tutorial/venv.html). After you have created and activated a new virtual environment, you should be able to install `nbtschematic`

```bash
pip3 install nbtschematic
```

The next lines starting from

```py
from nbtschematic import SchematicFile
```

are python commands and not shell commands. You need to start a python interpreter such as `python3` or `ipython3`. This is a tiny demonstration program that is meant as a simple example. You can then write more complicated python scripts to make changes to schema files. Please be aware that the MCEdit schematic format is only compatible with Minecraft 1.12, which is quite old now.

**Comment by cbs228** [comment]
Closing as issue appears to have been addressed.
