### ISSUE TITLE
*newbie*: Help!!

### ISSUE THREAD

**Issue by kofi2022** [cbs228/nbtschematic#5]
Thank you for helping me with the nbtschematic software! I have so much to learn! If you aren't aware I plan to remake make Nyc in Minecraft 1.12 1:3 scale to use the immersive vehicle mods and chisels and bits mod. It is basically a redo of BTE's NYC 1:1 scale with added mods. However I am a newbie and just starting with my python journey (You can tell from my previous questions). I have seen the post "Building 1:1 Scale Minecraft Replicas with Google Maps" by Nikhil Jha which was a year ago and used the editor tool as well as analyzing each part of the code he used for rotating each schematic file and implementing it into python by copying (newbie mistake). However from your previous reply and python errors, I have seen the extra things I can add to make the code more efficient, like the numpy.swapaxes(). I Honestly was a bit overwhelmed. My starting map is with a LGA Airport runway piece from the website https://minecraftart.netlify.app/ which I believe is all I need to start the project. Because of my determination, I wanted to speed up the process by asking you for a generic code for rotating the specific schematic map file so that I can use it for multiple maps which I plan to connect in the end with coordinates. I'm sure there is more that could have been shown in the post. This would be highly appreciated. Sorry for any misunderstandings.
Here are the Givens:
file name: 'LGA1.schematic'
dimensions: width(159) height(210) thickness(1).
Blocks: All
Entities: None
Block entities: None

**Comment by cbs228** [comment]
That sounds like an ambitious undertaking.

`nbtschematic` was written very narrowly to provide programmatic access to the save file format used within [MCEdit](https://www.mcedit.net/about.html). I had a very specific problem to solve, and `nbtschematic` is my solution to that problem. I don't really need it anymore; it is at best passively maintained. Data manipulation is beyond the scope of this package and will not be added.

MCEdit is a full-fledged GUI level editor. It provides simple affine transforms, including the ability to rotate. I would obtain MCEdit 2.0 and give that a try. MCEdit is also written in python. While it doesn't offer a formal API, you can always find and use its underlying python functions if you need to perform this operation programmatically.
