### ISSUE TITLE
How can I use "spruce_slab" ?

### ISSUE THREAD

**Issue by HLHTHoldWind** [cbs228/nbtschematic#6]
Some blocks' ids have ":" or have no ids
It's not an integer
How can I use these blocks?

**Comment by cbs228** [comment]
nbtschematic was designed to work with MCEdit schematics. As far as I am aware, the latest Minecraft version that MCEdit supports is v1.12. In v1.12, all blocks used numeric-only identifiers. The MCEdit schematic file format can't store anything else. (Minecraft v1.13 discontinued these numeric identifiers.)

You can still use MCEdit (and this tool) to design or modify worlds in Minecraft 1.12 format. You can then use Minecraft itself to convert the old level to the new format. **Careful**: no "take-backsies." Once you convert the level to a later version of Minecraft, there is no way to convert it back! If you want to use a block that does not exist in Minecraft v1.12, you'll need to use a placeholder block and "find and replace" it later. Minecraft has a built-in `/fill` command that can be used for this purpose, but the volume it can edit at once is quite limited.

I am curious if there are any other editors or alternatives that are compatible with more recent versions of Minecraft.

**Comment by HLHTHoldWind** [comment]
Yes, I understand.
I mean **spruce slab** also exists in 1.12
But I don't know how to enter the id with **" : "**
nbtschematic requires that I have to enter an integer

**Comment by cbs228** [comment]
Block IDs and data values for Minecraft 1.12 may be found at <https://minecraft.fandom.com/wiki/Java_Edition_data_values/Pre-flattening#Wooden_Slabs>. Use the block ID for the `blocks` field and the data value in the `data` field.

**Comment by HLHTHoldWind** [comment]
Thanks for this link.

I found that the **spruce_slab**'s **base id** is 126, and its **data value** is 1, 
but how can I mix these two ids into an **integer**? Because the **SchematicFile().blocks** requires an **integer**

`ValueError: invalid literal for int() with base 10: '126:1'`

Can you give an **example** with the **spruce_slab**?

Sorry I still don't understand well.

**Comment by cbs228** [comment]
You don't mix them. They are separate fields.

The schematic file has two separate `np.array`s for this.

* `SchematicFile.blocks[y,z,x]` is the base ID (or "block ID") for the given block
* `SchematicFile.data[y,z,x]` is the data value for the given block

The two arrays correspond index-for-index. The contents of both fields at the same `y,z,x` indices, together, represent one block. Other fields exist for block entities (sometimes called tile entities) like chests that need to contain additional data.

**Comment by HLHTHoldWind** [comment]
Thanks a lot :D

Now I finally understand how to use this package.

Thanks for your help 👍🏻
